[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://api.windy.com https://www.windy.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src * data:; font-src 'self'; connect-src *"
